# Generated by Django 3.2 on 2021-04-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'ProgrammingLanguage',
                'verbose_name_plural': 'ProgrammingLanguages',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='WorkingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'WorkingPlace',
                'verbose_name_plural': 'WorkingPlaces',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profileavatar/%Y/%m/%d')),
                ('about', models.TextField()),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=400, null=True)),
                ('programming_languages', models.ManyToManyField(to='main.ProgrammingLanguages')),
                ('working_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.workingplace')),
            ],
        ),
    ]
