# Generated by Django 3.2 on 2021-04-29 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, related_name='programming_languages', to='main.ProgrammingLanguages'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='main.workingplace'),
        ),
    ]
