# Generated by Django 3.2 on 2021-05-04 21:26

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('main', '0003_alter_userprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owner_projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_p', to='projects.projects'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.ManyToManyField(null=True, to='projects.Projects'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=99, size=[230, 230], upload_to='profileavatar/%Y/%m/%d'),
        ),
    ]
